#!/usr/bin/env python3
from os import stat
from re import S
import pygame
import random
import time
import sys

# help to use arrow cases

from pygame.locals import (
    RLEACCEL,
    K_q,
    K_d,
    K_x,
    K_RIGHT,
    K_LEFT,
    K_ESCAPE,
    KEYDOWN,
    QUIT,
)

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# initialize the size of the window here

pygame.mixer.init()
pygame.init()

class PlayerOne(pygame.sprite.Sprite):
    def __init__(self):
        # init the first player's position with self.surf.get_rect()
        # set it's texture with pygame.image.load()
        
    def update(self, pressed_keys):
        # move the player with arrow cases
    
    # set variables to be used later (like self.hp for exemple ?)

class PlayerTwo(pygame.sprite.Sprite):
    def __init__(self):
        # init the second player with the good width and height

    def update(self, pressed_keys):
        # move the player with arrow cases

class Bottle(pygame.sprite.Sprite):
    # init the bottle with speed and the widht and height

    def update(self):
        # destroy the bottle when hit the player

class Can(pygame.sprite.Sprite):
    def __init__(self):
        # init the can with speed and the widht and height 

    def update(self):
        # destroy the can when hit the player

class Background(pygame.sprite.Sprite):
    def __init__(self):
    # init the background

    def update(self):
        # update state of background 


def display_score(SCORE, X, player):
    # init the score of the player and display it

def game():
    # create the game with features and the gameplay

def display_game_over(PLAYER):
    # display the game over when the player die

def game_over(all_sprites, PLAYER):
    # init the game over loop
